//
//  AppConstants.swift
//  CurrencyConverter
//
//  Created by Lucas Werner Kuipers on 02/07/21.
//

import Foundation

struct Scenes {
    struct Conversion {
        static let title = NSLocalizedString("scenes.conversion.title", comment: "")
    }
    struct Selection {
        static let title = NSLocalizedString("scenes.selection.title", comment: "")
    }
}

struct Currency {
    static var conversionRates = [
        "USD": 1,
        "BRL": 5.04,
        "AUD": 1.340245,
        "EUR": 0.844365,
        "CAD": 1.243835,
        "CHF": 0.92613
    ]
    static var availableUnits = [
        "AED":"United Arab Emirates Dirham",
        "AFN":"Afghan Afghani",
        "ALL":"Albanian Lek",
        "AMD":"Armenian Dram",
        "ANG":"Netherlands Antillean Guilder",
        "AOA":"Angolan Kwanza",
        "ARS":"Argentine Peso",
        "AUD":"Australian Dollar",
        "AWG":"Aruban Florin",
        "AZN":"Azerbaijani Manat",
        "BAM":"Bosnia-Herzegovina Convertible Mark",
        "BBD":"Barbadian Dollar",
        "BDT":"Bangladeshi Taka",
        "BGN":"Bulgarian Lev",
        "BHD":"Bahraini Dinar",
        "BIF":"Burundian Franc",
        "BMD":"Bermudan Dollar",
        "BND":"Brunei Dollar",
        "BOB":"Bolivian Boliviano",
        "BRL":"Brazilian Real",
        "BSD":"Bahamian Dollar",
        "BTC":"Bitcoin",
        "BTN":"Bhutanese Ngultrum",
        "BWP":"Botswanan Pula",
        "BYN":"New Belarusian Ruble",
        "BYR":"Belarusian Ruble",
        "BZD":"Belize Dollar",
        "CAD":"Canadian Dollar",
        "CDF":"Congolese Franc",
        "CHF":"Swiss Franc",
        "CLF":"Chilean Unit of Account (UF)",
        "CLP":"Chilean Peso",
        "CNY":"Chinese Yuan",
        "COP":"Colombian Peso",
        "CRC":"Costa Rican Colón",
        "CUC":"Cuban Convertible Peso",
        "CUP":"Cuban Peso",
        "CVE":"Cape Verdean Escudo",
        "CZK":"Czech Republic Koruna",
        "DJF":"Djiboutian Franc",
        "DKK":"Danish Krone",
        "DOP":"Dominican Peso",
        "DZD":"Algerian Dinar",
        "EGP":"Egyptian Pound",
        "ERN":"Eritrean Nakfa",
        "ETB":"Ethiopian Birr",
        "EUR":"Euro",
        "FJD":"Fijian Dollar",
        "FKP":"Falkland Islands Pound",
        "GBP":"British Pound Sterling",
        "GEL":"Georgian Lari",
        "GGP":"Guernsey Pound",
        "GHS":"Ghanaian Cedi",
        "GIP":"Gibraltar Pound",
        "GMD":"Gambian Dalasi",
        "GNF":"Guinean Franc",
        "GTQ":"Guatemalan Quetzal",
        "GYD":"Guyanaese Dollar",
        "HKD":"Hong Kong Dollar",
        "HNL":"Honduran Lempira",
        "HRK":"Croatian Kuna",
        "HTG":"Haitian Gourde",
        "HUF":"Hungarian Forint",
        "IDR":"Indonesian Rupiah",
        "ILS":"Israeli New Sheqel",
        "IMP":"Manx pound",
        "INR":"Indian Rupee",
        "IQD":"Iraqi Dinar",
        "IRR":"Iranian Rial",
        "ISK":"Icelandic Króna",
        "JEP":"Jersey Pound",
        "JMD":"Jamaican Dollar",
        "JOD":"Jordanian Dinar",
        "JPY":"Japanese Yen",
        "KES":"Kenyan Shilling",
        "KGS":"Kyrgystani Som",
        "KHR":"Cambodian Riel",
        "KMF":"Comorian Franc",
        "KPW":"North Korean Won",
        "KRW":"South Korean Won",
        "KWD":"Kuwaiti Dinar",
        "KYD":"Cayman Islands Dollar",
        "KZT":"Kazakhstani Tenge",
        "LAK":"Laotian Kip",
        "LBP":"Lebanese Pound",
        "LKR":"Sri Lankan Rupee",
        "LRD":"Liberian Dollar",
        "LSL":"Lesotho Loti",
        "LTL":"Lithuanian Litas",
        "LVL":"Latvian Lats",
        "LYD":"Libyan Dinar",
        "MAD":"Moroccan Dirham",
        "MDL":"Moldovan Leu",
        "MGA":"Malagasy Ariary",
        "MKD":"Macedonian Denar",
        "MMK":"Myanma Kyat",
        "MNT":"Mongolian Tugrik",
        "MOP":"Macanese Pataca",
        "MRO":"Mauritanian Ouguiya",
        "MUR":"Mauritian Rupee",
        "MVR":"Maldivian Rufiyaa",
        "MWK":"Malawian Kwacha",
        "MXN":"Mexican Peso",
        "MYR":"Malaysian Ringgit",
        "MZN":"Mozambican Metical",
        "NAD":"Namibian Dollar",
        "NGN":"Nigerian Naira",
        "NIO":"Nicaraguan Córdoba",
        "NOK":"Norwegian Krone",
        "NPR":"Nepalese Rupee",
        "NZD":"New Zealand Dollar",
        "OMR":"Omani Rial",
        "PAB":"Panamanian Balboa",
        "PEN":"Peruvian Nuevo Sol",
        "PGK":"Papua New Guinean Kina",
        "PHP":"Philippine Peso",
        "PKR":"Pakistani Rupee",
        "PLN":"Polish Zloty",
        "PYG":"Paraguayan Guarani",
        "QAR":"Qatari Rial",
        "RON":"Romanian Leu",
        "RSD":"Serbian Dinar",
        "RUB":"Russian Ruble",
        "RWF":"Rwandan Franc",
        "SAR":"Saudi Riyal",
        "SBD":"Solomon Islands Dollar",
        "SCR":"Seychellois Rupee",
        "SDG":"Sudanese Pound",
        "SEK":"Swedish Krona",
        "SGD":"Singapore Dollar",
        "SHP":"Saint Helena Pound",
        "SLL":"Sierra Leonean Leone",
        "SOS":"Somali Shilling",
        "SRD":"Surinamese Dollar",
        "STD":"São Tomé and Príncipe Dobra",
        "SVC":"Salvadoran Colón",
        "SYP":"Syrian Pound",
        "SZL":"Swazi Lilangeni",
        "THB":"Thai Baht",
        "TJS":"Tajikistani Somoni",
        "TMT":"Turkmenistani Manat",
        "TND":"Tunisian Dinar",
        "TOP":"Tongan Pa'anga",
        "TRY":"Turkish Lira",
        "TTD":"Trinidad and Tobago Dollar",
        "TWD":"New Taiwan Dollar",
        "TZS":"Tanzanian Shilling",
        "UAH":"Ukrainian Hryvnia",
        "UGX":"Ugandan Shilling",
        "USD":"United States Dollar",
        "UYU":"Uruguayan Peso",
        "UZS":"Uzbekistan Som",
        "VEF":"Venezuelan Bolívar Fuerte",
        "VND":"Vietnamese Dong",
        "VUV":"Vanuatu Vatu",
        "WST":"Samoan Tala",
        "XAF":"CFA Franc BEAC",
        "XAG":"Silver (troy ounce)",
        "XAU":"Gold (troy ounce)",
        "XCD":"East Caribbean Dollar",
        "XDR":"Special Drawing Rights",
        "XOF":"CFA Franc BCEAO",
        "XPF":"CFP Franc",
        "YER":"Yemeni Rial",
        "ZAR":"South African Rand",
        "ZMK":"Zambian Kwacha (pre-2013)",
        "ZMW":"Zambian Kwacha",
        "ZWL":"Zimbabwean Dollar"
    ]
    
    static let codeToCountry = [
      "AED" : "United Arab Emirates",
      "AFN" : "Afghanistan",
      "ALL" : "Albania",
      "AMD" : "Armenia",
      "ANG" : "Netherlands Antilles",
      "AOA" : "Angola",
      "ARS" : "Argentina",
      "AUD" : "Australia, Australian Antarctic Territory, Christmas Island, Cocos (Keeling) Islands, Heard and McDonald Islands, Kiribati, Nauru, Norfolk Island, Tuvalu",
      "AWG" : "Aruba",
      "AZN" : "Azerbaijan",
      "BAM" : "Bosnia and Herzegovina",
      "BBD" : "Barbados",
      "BDT" : "Bangladesh",
      "BGN" : "Bulgaria",
      "BHD" : "Bahrain",
      "BIF" : "Burundi",
      "BMD" : "Bermuda",
      "BND" : "Brunei",
      "BOB" : "Bolivia",
      "BOV" : "Bolivia",
      "BRL" : "Brazil",
      "BSD" : "Bahamas",
      "BTN" : "Bhutan",
      "BWP" : "Botswana",
      "BYR" : "Belarus",
      "BZD" : "Belize",
      "CAD" : "Canada",
      "CDF" : "Democratic Republic of Congo",
      "CHE" : "Switzerland",
      "CHF" : "Switzerland, Liechtenstein",
      "CHW" : "Switzerland",
      "CLF" : "Chile",
      "CLP" : "Chile",
      "CNY" : "Mainland China",
      "COP" : "Colombia",
      "COU" : "Colombia",
      "CRC" : "Costa Rica",
      "CUP" : "Cuba",
      "CVE" : "Cape Verde",
      "CYP" : "Cyprus",
      "CZK" : "Czech Republic",
      "DJF" : "Djibouti",
      "DKK" : "Denmark, Faroe Islands, Greenland",
      "DOP" : "Dominican Republic",
      "DZD" : "Algeria",
      "EEK" : "Estonia",
      "EGP" : "Egypt",
      "ERN" : "Eritrea",
      "ETB" : "Ethiopia",
      "EUR" : "European Union, see eurozone",
      "FJD" : "Fiji",
      "FKP" : "Falkland Islands",
      "GBP" : "United Kingdom",
      "GEL" : "Georgia",
      "GHS" : "Ghana",
      "GIP" : "Gibraltar",
      "GMD" : "Gambia",
      "GNF" : "Guinea",
      "GTQ" : "Guatemala",
      "GYD" : "Guyana",
      "HKD" : "Hong Kong Special Administrative Region",
      "HNL" : "Honduras",
      "HRK" : "Croatia",
      "HTG" : "Haiti",
      "HUF" : "Hungary",
      "IDR" : "Indonesia",
      "ILS" : "Israel",
      "INR" : "Bhutan, India",
      "IQD" : "Iraq",
      "IRR" : "Iran",
      "ISK" : "Iceland",
      "JMD" : "Jamaica",
      "JOD" : "Jordan",
      "JPY" : "Japan",
      "KES" : "Kenya",
      "KGS" : "Kyrgyzstan",
      "KHR" : "Cambodia",
      "KMF" : "Comoros",
      "KPW" : "North Korea",
      "KRW" : "South Korea",
      "KWD" : "Kuwait",
      "KYD" : "Cayman Islands",
      "KZT" : "Kazakhstan",
      "LAK" : "Laos",
      "LBP" : "Lebanon",
      "LKR" : "Sri Lanka",
      "LRD" : "Liberia",
      "LSL" : "Lesotho",
      "LTL" : "Lithuania",
      "LVL" : "Latvia",
      "LYD" : "Libya",
      "MAD" : "Morocco, Western Sahara",
      "MDL" : "Moldova",
      "MGA" : "Madagascar",
      "MKD" : "Former Yugoslav Republic of Macedonia",
      "MMK" : "Myanmar",
      "MNT" : "Mongolia",
      "MOP" : "Macau Special Administrative Region",
      "MRO" : "Mauritania",
      "MTL" : "Malta",
      "MUR" : "Mauritius",
      "MVR" : "Maldives",
      "MWK" : "Malawi",
      "MXN" : "Mexico",
      "MXV" : "Mexico",
      "MYR" : "Malaysia",
      "MZN" : "Mozambique",
      "NAD" : "Namibia",
      "NGN" : "Nigeria",
      "NIO" : "Nicaragua",
      "NOK" : "Norway",
      "NPR" : "Nepal",
      "NZD" : "Cook Islands, New Zealand, Niue, Pitcairn, Tokelau",
      "OMR" : "Oman",
      "PAB" : "Panama",
      "PEN" : "Peru",
      "PGK" : "Papua New Guinea",
      "PHP" : "Philippines",
      "PKR" : "Pakistan",
      "PLN" : "Poland",
      "PYG" : "Paraguay",
      "QAR" : "Qatar",
      "RON" : "Romania",
      "RSD" : "Serbia",
      "RUB" : "Russia, Abkhazia, South Ossetia",
      "RWF" : "Rwanda",
      "SAR" : "Saudi Arabia",
      "SBD" : "Solomon Islands",
      "SCR" : "Seychelles",
      "SDG" : "Sudan",
      "SEK" : "Sweden",
      "SGD" : "Singapore",
      "SHP" : "Saint Helena",
      "SKK" : "Slovakia",
      "SLL" : "Sierra Leone",
      "SOS" : "Somalia",
      "SRD" : "Suriname",
      "STD" : "São Tomé and Príncipe",
      "SYP" : "Syria",
      "SZL" : "Swaziland",
      "THB" : "Thailand",
      "TJS" : "Tajikistan",
      "TMM" : "Turkmenistan",
      "TND" : "Tunisia",
      "TOP" : "Tonga",
      "TRY" : "Turkey",
      "TTD" : "Trinidad and Tobago",
      "TWD" : "Taiwan and other islands that are under the effective control of the Republic of China (ROC)",
      "TZS" : "Tanzania",
      "UAH" : "Ukraine",
      "UGX" : "Uganda",
      "USD" : "American Samoa, British Indian Ocean Territory, Ecuador, El Salvador, Guam, Haiti, Marshall Islands, Micronesia, Northern Mariana Islands, Palau, Panama, Puerto Rico, East Timor, Turks and Caicos Islands, United States, Virgin Islands",
      "USN" : "United States",
      "USS" : "United States",
      "UYU" : "Uruguay",
      "UZS" : "Uzbekistan",
      "VEB" : "Venezuela",
      "VND" : "Vietnam",
      "VUV" : "Vanuatu",
      "WST" : "Samoa",
      "XAF" : "Cameroon, Central African Republic, Congo, Chad, Equatorial Guinea, Gabon",
      "XAG" : "",
      "XAU" : "",
      "XBA" : "",
      "XBB" : "",
      "XBC" : "",
      "XBD" : "",
      "XCD" : "Anguilla, Antigua and Barbuda, Dominica, Grenada, Montserrat, Saint Kitts and Nevis, Saint Lucia, Saint Vincent and the Grenadines",
      "XDR" : "International Monetary Fund",
      "XFO" : "Bank for International Settlements",
      "XFU" : "International Union of Railways",
      "XOF" : "Benin, Burkina Faso, Côte d'Ivoire, Guinea-Bissau, Mali, Niger, Senegal, Togo",
      "XPD" : "",
      "XPF" : "French Polynesia, New Caledonia, Wallis and Futuna",
      "XPT" : "",
      "XTS" : "",
      "XXX" : "",
      "YER" : "Yemen",
      "ZAR" : "South Africa",
      "ZMK" : "Zambia",
      "ZWD" : "Zimbabwe"]
}
